name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  INPUT_FOLDER: "test_input_folder"
  OUTPUT_FILE: "file_list.md"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Create a Markdown file with a list of all filenames in the input folder
        run: |
          echo "# List of files in $INPUT_FOLDER" > $OUTPUT_FILE
          for file in $(ls $INPUT_FOLDER); do
            echo "- $file" >> $OUTPUT_FILE
          done
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add $OUTPUT_FILE
          git commit -m "Add list of files in input folder"
          git push origin HEAD:${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}