name: CI
on:
  push:
    branches: [ "main, dev" ]
  workflow_dispatch:

permissions:
  contents: write

env:
  INPUT_FOLDERS: "test_input_folder/dvpohdkv,test_input_folder/jtpcfazn,test_input_folder/lurnydqg"
  OUTPUT_FILE: "file_list.md"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Create a Markdown file with a list of all filenames in the input folder
        run: |
          IFS=',' read -r -a folders <<< "$INPUT_FOLDERS"
          echo "# List of files in $INPUT_FOLDER" > $OUTPUT_FILE
          for folder in "${folders[@]}"; do
            echo "## $folder" >> $OUTPUT_FILE
            for file in $(ls $folder); do
              echo "- $file" >> $OUTPUT_FILE
            done
          done
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add $OUTPUT_FILE
          git commit -m "Add list of files in input folder"
          git push origin HEAD:${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}